# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
sudo: required
services: docker
language: rust

env:
  global:
    - CRATE_NAME=languageclient
    - secure: eWJeA/cgx+RqY6jny1wtw4LErLy5leXYFvcfmGzwn8jGzDuUYt9S86GpMWamhKXsWZnUq3tdaCUFEThqd72nbQDd5tXhlKDAHQO6imo7zkszERv2mBRbDJwufYnj9J41OSyXk2MrJKerOTkD0HX5RmHXpY/wZf5ESSY5KamWBrqEOCLHdkT0QFD8Yqa9oCrfX3pI16b70rbZF60TSL5sE4neU9ai771fWyl0cGgO6QrpmW+J2fzC+gEtvDuBVoOUsfLlUBAEdylO6FIEEZy7i+HFFBCXYKtJIffdlMWKg9nogDU2ZqEtcPCgbc6HbhTCMPNPm/JlXUPw2zwb6tCO/IlMe3heLMPs+dfzbUdSCxTWicPzdzbZCjA4iUvDE2/vailVdKm72jSbm9ja7Vr9H5Y+IQpH3uncAAyE/q6fpKUh6uVRgKPA/5bULgzOwM0EuwWpyMC2iJvu/SGmrsUYZzztuB61p+G+TGlqrKFw9IfzfzrKlRDkMHYRbbSGQuB7NEYRV2Qn+4VavLjw+bshiK+8BqfjfFBdp/v1u8D06MhE1f4NnK9jh7NUm7qipfTU+HgZUauYN54T8CeljtyaynUeTDy2FNnK+zoA8WfxxZSnN7z8XOeAQESZWCRx3gG6ES6hChkwNxsyub9cU+VGCKvPgikXQzaWZ2EvOzGrpz8=

matrix:
  include:
    # Linux
    - env: TARGETS=i686-unknown-linux-musl:x86_64-unknown-linux-musl:aarch64-unknown-linux-musl:x86_64-pc-windows-gnu

    # OSX
    - env: TARGETS=x86_64-apple-darwin
      os: osx

if: tag IS present

branches:
  except:
    - /binary-.*/

script:
    - true

deploy:
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: Dr/oCr65KsSjcDk21+CS7cZ/UR/ktncwDLsQIF/UyFC0bCP5MFbQ76Cz7Dy460hMtjCiy/X4QukxtiF0oeaOvi1szbo29s1KYjc9xPVhI1roQUyGghkGzo+V5Ncum3pwKF1Mb/kotikh2QSFQJYA3o32HhMNVb+1bApD+bwyAsGlnlAYYWQy+EcIDByhG9B4HB2pScoblyPmbgQPftc/E3ldKkm4iPNiNNa9T/rlXazNOkuiAqbRR/qBI4sSVAFFvfzvEcva4k5X8wzWfdsiDk9HKnNL7iDzdMMExSOoIKoet6jK3E3f2VbwD7tRw+We2cB+EBrW7xtkcck/BbEtnXhiWpt+Gg4qxXjZ6RVXgVw9tH0CGp2FjZ6B2DQ/chtgzIzLE+iuhJwhRqJ+7IW7LgNrnEsi6QelCiNKsm0aqXEpU5BVoBXxBegJHgHhunkKPpqmhYps5KsH4RPzrduqk2LHlYriwaGumcEnOVXzoJJs0NE6RaFzwl5cxmiKxC8tl1/dE4w2WmYM8n3yMmfbCd520bTQbvOe68k/8iV7gqZmOnWX//PLJ6Zf+v7T0yhaFC8Oj8ueWUCCSd7TAC3rHxd52BVZnQF1xXosiiN2PyWGZGbxaO1Qh7UbF1Xk+ot2pwEsP5Q8h155DlYJ/3mMzLvSi6Cp+78YKsoFlpfDy6w=
  file_glob: true
  file: bin/$CRATE_NAME-$TRAVIS_TAG-*
  overwrite: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true

before_deploy:
  - bash ci/install.sh
  - bash ci/before_deploy.sh

cache:
    cargo: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

# vim: tabstop=2
