[package]
name = "languageclient"
version = "0.1.35"
authors = ["Junfeng Li <autozimu@gmail.com>"]
description = "Language Server Protocol (LSP) support for vim and neovim"
publish = false

[dependencies]
failure = "*"
log = "*"
log4rs = "*"
structopt = "*"
structopt-derive = "*"
libc = "*"
lazy_static = "*"
chrono = "*"
maplit = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"

jsonrpc-core = "*"
languageserver-types = "*"
url = "*"
pathdiff = "*"
diff = "*"
regex = "*"
glob = "*"

[package.metadata.release]
no-dev-version = true
pre-release-replacements = [
    { file = "install.sh", search = "version=.*", replace = "version={{version}}" },
    { file = "install.ps1", search = "version = '.*'", replace = "version = '{{version}}'" }
]
pre-release-hook = 'ci/release-hook.sh'
